version: "3.8"
services:

  api:
    build:
      context: ./api
    ports:
      - 9229:9229
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - API_PORT=5000
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - JIRA_USER
      - JIRA_TOKEN
      - JIRA_HOST

    command: npm run debug
    depends_on:
      - postgres

  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
      - nginx
      - postgres

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT:-3001}:80"
  
  postgres:
    image: postgres:12
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_development
