version: "3.8"
services:  
  api:
    build:
      context: ./api
    ports:
      - 9229:9229
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - NODE_ENV=development
      - API_PORT=3000
    command: npm run debug
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=database_development
  