name: test-k14s

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: k14s/setup-k14s-action@v1
      - run: |
          ytt version
          kbld version
          kapp version
          kwt version
          imgpkg version
          vendir version
