name: test

on:
  push:
    branches:
    - develop
  pull_request:

jobs:

  unit-test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint:check
    - run: npm run test:unit

  unit-test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint:check
    - run: npm run test:unit

  integration-test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup database
      run: |
        cp default.env .env
        NODE_ENV=test npm run db:setup
    - run: npx lerna run test:integration
